### PR TITLE
Added laravel 7 support

### PR DESCRIPTION
**Pull request by fhsinchy**

### CODE REVIEW

**Comment by jimmyt2003** [comment]
can we merge this?

**Comment by fhsinchy** [comment]
Yes you can I think. It works on our project flawlessly.
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Mar 16, 2020, 12:57 AM by notifications@github.com:

**Comment by fhsinchy** [comment]
> can we merge this?

It works flawlessly in our product. I think it can be merged.

**Comment by fhsinchy** [comment]
> can we merge this?

Well it works flawlessly in our product :smile:

**Comment by nicolaslopezj** [comment]
Already merged

**Pull request closed without merging**
