### PR TITLE
fix broken bindings after searchable trait is applied

### PR DESCRIPTION
**Pull request by Tamrael**
let laravel rawSelect handle the bindings to fix breaking the order of them
as the Database-Query-Builder has an internal structure of bindings (select, join, raw, etc.) that is never exposed to the Eloquent-Query-Builder we can't and should not handle the bindings on our own as we would mess up the order if external scopes where applied

### CODE REVIEW

**Comment by Tamrael** [comment]
fixes #93

**Comment by nicolaslopezj** [comment]
Can someone confirm this works correctly?

**Comment by Tamrael** [comment]
Query:
`select `id`, `first_name`, `name`, `email` from (select `users`.*, max((case when LOWER(`users`.`first_name`) LIKE ? then 150 else 0 end) + (case when LOWER(`users`.`first_name`) LIKE ? then 50 else 0 end) + (case when LOWER(`users`.`first_name`) LIKE ? then 10 else 0 end) + (case when LOWER(`users`.`name`) LIKE ? then 150 else 0 end) + (case when LOWER(`users`.`name`) LIKE ? then 50 else 0 end) + (case when LOWER(`users`.`name`) LIKE ? then 10 else 0 end) + (case when LOWER(`users`.`email`) LIKE ? then 75 else 0 end) + (case when LOWER(`users`.`email`) LIKE ? then 25 else 0 end) + (case when LOWER(`users`.`email`) LIKE ? then 5 else 0 end)) as relevance from `users` where `users`.`online` = ? group by `users`.`id` having relevance >= 6.25 order by `relevance` desc) as `users` where `users`.`online` = ?`

Old Behavior:
Bindings:
`[1,"test","test%","%test%","test","test%","%test%","test","test%","%test%",1,1,1]`

New Behavior Bindings:
`["test","test%","%test%","test","test%","%test%","test","test%","%test%",1,1,1]`

there is still a problem with duplicate bindings added because the setBindings that should merge the two queries doesn't actually overwrite the old bindings. if i only call setBindings on the $query->getBindings() the Bindings are as they should be but i can't confirm that this is a behavior that is consistent for laravel versions other than 5.4

**Comment by markwalet** [comment]
This really should be merged.

**Pull request merged**
